Add write file stream
FoundatioFx/Foundatio pull request #290
Opened 2023-09-04 15:54 UTC by garcipat

To write files in the file storage, usually you want to write to the stream directly, not pass the stream over as an argument.

This PR adds an overload where you can tell if you want to use the stream you get to read or to write only. 

There should be no breaking changes on existing things, but a new method is added, therefore implementations have ti implementa that.

2023-09-04 15:54 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/FoundatioFx/Foundatio?pullRequest=290) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/FoundatioFx/Foundatio?pullRequest=290) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/FoundatioFx/Foundatio?pullRequest=290) it.</sub>

2023-09-04 19:37 UTC, ejsmith requested changes
Looks great! Thank you! Only bit of feedback is just to deprecate the old method so we can get rid of it since it is redundant now.

2023-09-04 19:37 UTC, ejsmith commented on src/Foundatio/Storage/FolderFileStorage.cs
> +        public Task<Stream> GetFileStreamAsync(string path, FileAccess fileAccess, CancellationToken cancellationToken = default) {
I like this signature. I would say that we should mark the current method as deprecated so that we can get rid of it on the next major version.

2023-09-05 13:46 UTC, merged

2023-09-05 13:48 UTC, ejsmith commented
Thank you @garcipat! Will you be able to create PRs for the other storage implementations as well?

2023-09-05 15:07 UTC, garcipat commented
What you mean? I went though all implementations of IFileStorage and added that. Or did I miss something?

2023-09-05 16:23 UTC, ejsmith commented
Yeah, not sure which ones you are using, but there are several `IFileStorage` implementations for S3, Azure Blob Storage, SshNet, Minio, Aliyun, and Redis. If you are using any of those and want to do PRs for those, that would be awesome. :-) If you are feeling really generous and want to go do PRs for all of them that would be crazy cool. :-)

2023-09-05 16:51 UTC, garcipat commented
Yes I rememeber. I means whats why we use fhe package. But I didnt realize its in other repositories. will see what I can do. Depends on how complicate it is with the other things. Also I dont know if I can test it with all of them. Will see. I will at least intend it.

2023-09-22 15:58 UTC, garcipat commented
> We probably want FileAccess fileAccess to default to Read, otherwise this is a pretty big breaking change. I upgraded a project and had quite a few compiler errors (warnings as errors on). The default for all of them was read. Thoughts?

Currently the implementation without the file access does use read to prevemt a breaking change. But we could set a default value if you would like to if we change it again anyway. 
I think it would be preferable to set it intentionally when changing from the obsolete method since its not obvious that the stream is only reading if nothing set. You only discover that when trying to write and it doesnt work.

 But thats personal preference I guess.

2023-09-22 17:56 UTC, ejsmith commented
It's not a breaking change because the old signature didn't have fileaccess on it and you would hit that one.

The new method requires FileAccess and it should continue to do so even when we remove the old one.

Also, @garcipat is going to update the enum to be a foundatio enum so that we control what stream modes are available. Which we said would just be read or write for now.